app/views/fields/active_storage/_index.html.erb
I was trying to preview an image file in a resource index view, and was hitting two errors:
First, the `_item.html.erb` partial wasn't being found, and secondly, the `field` and `attachment` locals weren't available. Looking at the source code, it seems like this is a simple syntax issue in ` app/views/fields/active_storage/_index.html.erb`, particularly since when fixed, that file becomes identical to  `app/views/fields/active_storage/_show.html.erb`.
My supposition is that this is simply a typo that hasn't been fixed, so I'm submitting a PR to fix it. If I'm missing something and it's deliberate, feel free to ignore me!
=> Fix apparently error-y partial

app/views/fields/active_storage/_item.html.erb
I turned off autoplay because I'd like to browse my admin without hearing audio. It was especially frustrating on a model with multiple audio files attached to one record - they all start autoplaying at the same time, overlapping each other.
=> don't autoplay audio on show pages

example-project/Gemfile.lock, lib/administrate/field/active_storage.rb
`show_in_index?` always return true if destroy path is set causing unexpected behaviour
This is caused by a bug in the active storage field model that check the key of `destroy_path` instead of the `show_in_index`.
Fixed by fetching `show_in_index` options instead and set the default to false.
=> fix(show in index): show_in_index? always return true

app/views/fields/active_storage/_form.html.erb, contribute.md
Adds compatibility with the [nested_has_many gem](https://github.com/nickcharlton/administrate-field-nested_has_many) which renders fields with nil data.
Fixes #13
=> Prevent items rendering with nil field data

app/views/fields/active_storage/_index.html.erb, app/views/fields/active_storage/_item.html.erb, lib/administrate/field/active_storage.rb
When using this gem rails was warning for 
> DEPRECATION WARNING: Active Storage's ImageProcessing transformer doesn't support :combine_options, as it always generates a single ImageMagick command. Passing :combine_options will not be supported in Rails 6.1.
This PR fixes that by using the new resize option of Array instead of String as per [Rails Guides](https://guides.rubyonrails.org/v6.0/active_storage_overview.html#transforming-images)
=> Change resize option to conform with rails 6

README.md
Update the [Prevent N+1 queries](https://github.com/Dreamersoul/administrate-field-active_storage#prevent-n1-queries) of the readme.
Overloading `scoped_resouce` looks better than overloading `index` action.
Actually the `index` action is doing more than just paging:
https://github.com/thoughtbot/administrate/blob/95b0153dd523af55c47df32b0a28ca4d1bb11fa6/app/controllers/administrate/application_controller.rb#L5
=> Update readme of n+1

README.md
Problem
-------
The example for how to use `show_preview_size` was wrong and caused apps
to crash when using that option as directed.
Solution
--------
Update the docs to have the correct usage of `show_preview_size` in the
sample code.
Fixes Issue #2
=> Update readme docs around `show_preview_size` usage

app/views/fields/active_storage/_item.html.erb, contribute.md
I uploaded a GIF that's in webp format. ActiveStorage treats it as an image but I can preview it due to https://edgeapi.rubyonrails.org/classes/ActiveStorage/InvariableError.html
=> Support previews for images that ImageMagick doesn't support

app/views/fields/active_storage/_item.html.erb
- downlolad original attachment by clicking on it
- only show the number of attachments if greater than 1; show `-` if 0
- show filename in tooltip text
index (with tooltip on mouse hover):
show (with tooltip on mouse hover):
Fixes #29
=> Link to download attachment + hide count if 0 or 1

README.md, app/views/fields/active_storage/_form.html.erb, app/views/fields/active_storage/_index.html.erb, app/views/fields/active_storage/_item.html.erb, app/views/fields/active_storage/_items.html.erb, app/views/fields/active_storage/_preview.html.erb, app/views/fields/active_storage/_show.html.erb, lib/administrate/field/active_storage.rb
Preview display:
-  `index_display_preview` replaces `show_in_index` as the term "show" can be ambiguous with the `show` action
- `show_display_preview` replaces `url_only` for coherence. This also fixes the issue that `url_only` applied to the `index` and was thus interfering with `show_in_index`.
- both values default to `true`
Preview size:
- centralizes the size defaults into the library code
- set separate default sizes `index_preview_size` and `show_preview_size` for the `index` and `show` actions, respectively
- adds more responsiveness to video attachments
Displaying number of attachments in index action (`index_display_count`):
- defaults to `true` if number of attachments is not 1
Show:
- display "No attachment" if no attachment present
Edit:
- change "Add" text to "Replace" if …
=> Attachment display tweaks

README.md, app/views/fields/active_storage/_form.html.erb, app/views/fields/active_storage/_item.html.erb, example-project/app/controllers/admin/users_controller.rb, example-project/app/controllers/users_controller.rb, example-project/app/dashboards/user_dashboard.rb, example-project/config/routes.rb, lib/administrate/field/active_storage.rb
- removes the need to explicitly configure the field when defining the destroy route in a standard manner
- this convention can be overridden/customized with more flexibility by giving access to the Administrate `namespace`, `record` and `attachment` objects
- cleans up the code related to the attachment destroy action
- I also took the opportunity to improve the definition of `many?`
NB: The PR currently has a caveat, an error is thrown if the expected route is not defined whereas instead, it would be preferable to just disable the button. That is because in the definition of `destroy_url` I don't know how to check whether the route exists (as it is written in a general way without using a named route).
=> Destroy action improvements

README.md
Update [Removing/Deleting an Attachment ](https://github.com/Dreamersoul/administrate-field-active_storage#removingdeleting-an-attachment )of the readme.
Although it is written that the example is for a `has_many_attached` It takes me a while to notice that I need to remove the params of the code to things work. I believe that another example can help others.
=> Add example of removing/deleting attachment for 'has_one_attached' type

app/views/fields/active_storage/_index.html.erb, lib/administrate/field/active_storage.rb
I first noticed there were a lot of repeated queries in my logs when viewing my dashboard index displaying active storage attachment previews, in spite of using `.with_attached_XXX` in the administrate controller.
I haven't quite understood why `attachments.present?` leads to N+1 queries, and why it's not the case when querying `attachments.count`. But anyway I got it fixed by replacing `attachments.present?` with `attached?`. This was further confirmed using the [Bullet](https://github.com/flyerhzm/bullet/) library.
=> Fix N+1 queries on index page

app/views/fields/active_storage/_item.html.erb
This prevents accidental data loss by making an alert for the user to confirm that they want to delete the attachment
=> Add confirmation alert when deleting attachment

contribute.md, lib/administrate/field/active_storage.rb
`combine_options` for `ImageProcessingTransformer` is deprecated as of Rails 6.1. See issue #47.
This resolves the warning: "Active Storage's ImageProcessing transformer doesn't support :combine_options, as it always generates a single ImageMagick command. Passing :combine_options will not be supported in Rails 6.1".
=> Resolve variant combine_options deprecation

lib/administrate/field/active_storage.rb
If the same blob is attached to many records, the blob is shown as many times when viewing one of these records:
With this PR the image shows up a single time at it should:
=> Fix duplication bug when same blob is attached to several records

README.md
It seems that the way to specify Gem's version is wrong.
ref: https://bundler.io/gemfile.html
=> fix(README): fix the sample code of specifying version for Rails 5

app/views/fields/active_storage/_index.html.erb, app/views/fields/active_storage/_preview.html.erb
Fixes #79 
There is no functional change, all inline styles are now inside tags where nonces are added.
Still not a pretty solution with inline styles but at least no errors when using CSP.
=> CSP compatibility by using only inline style tags with nonce

README.md, app/assets/stylesheets/administrate-field-active_storage/application.css, app/views/fields/active_storage/_index.html.erb, app/views/fields/active_storage/_items.html.erb, app/views/fields/active_storage/_preview.html.erb, lib/administrate/field/active_storage.rb
Add ability to use new (Rails 7) named variants for previewing images
To make this feasible inline CSS needed to go as well
It might be necessary to add to `app/assets/config/manifest.js`:
```
//= link administrate-field-active_storage/application.css' in 'app/assets/config/manifest.js
```
Fixes #90
=> Add ability to use new named variants for previewing images

app/views/fields/active_storage/_item.html.erb, app/views/fields/active_storage/_items.html.erb
There is some documentation for passing
a removable boolean, but there is no
way to pass this boolean through the
Administrate dashboard setup. It looks
like the Remove feature was implemented
through the `destroy_url` option instead.
This removes all references to the
`removable` boolean.
=> Remove references to removable

README.md, app/views/fields/active_storage/_preview.html.erb, contribute.md
The current implementation always displays a variant if an image is variable regardless of setting `show_preview_variant` to `nil`.
```
Field::ActiveStorage.with_options(show_preview_variant: nil)
```
This change allows us to show the original image by passing `false`.
```
Field::ActiveStorage.with_options(show_preview_variant: false)
```
Though the behavioral difference between `nil` and `false` is subtle, it somewhat aligns with the Action View's `layout` method.
> https://api.rubyonrails.org/classes/ActionView/Layouts/ClassMethods.html#method-i-layout
> - false: There is no layout
> - nil: Force default layout behavior with inheritance
=> Add an ability to display original images

README.md, app/views/fields/active_storage/_index.html.erb, app/views/fields/active_storage/_item.html.erb, app/views/fields/active_storage/_items.html.erb, lib/administrate/field/active_storage.rb
Thanks for this amazing gem!
This PR adds a new option called `index_preview_only`. If set to true, it will suppress the rendering of the filename and destroy link for previews on index pages. I figured I'm not the only one who would benefit from the option to have "just the image".
Let me know if I've broken any conventions or you need anything updating.
=> Add index_preview_only option
